import * as Lexer from './lexer';
export declare function nullValue(value: number[], index: number): Lexer.Token;
export declare function booleanValue(value: number[], index: number): Lexer.Token;
export declare function guidValue(value: any, index: any): Lexer.Token;
export declare function sbyteValue(value: number[], index: number): Lexer.Token;
export declare function byteValue(value: number[], index: number): Lexer.Token;
export declare function int16Value(value: number[], index: number): Lexer.Token;
export declare function int32Value(value: number[], index: number): Lexer.Token;
export declare function int64Value(value: number[], index: number): Lexer.Token;
export declare function decimalValue(value: number[], index: number): Lexer.Token;
export declare function doubleValue(value: number[], index: number): Lexer.Token;
export declare function singleValue(value: number[], index: number): Lexer.Token;
export declare function stringValue(value: number[], index: number): Lexer.Token;
export declare function durationValue(value: number[], index: number): Lexer.Token;
export declare function binaryValue(value: number[], index: number): Lexer.Token;
export declare function dateValue(value: number[], index: number): Lexer.Token;
export declare function dateTimeOffsetValue(value: number[], index: number): Lexer.Token;
export declare function timeOfDayValue(value: number[], index: number): Lexer.Token;
export declare function positionLiteral(value: number[], index: number): Lexer.Token;
export declare function pointData(value: number[], index: number): Lexer.Token;
export declare function lineStringData(value: number[], index: number): Lexer.Token;
export declare function ringLiteral(value: number[], index: number): Lexer.Token;
export declare function polygonData(value: number[], index: number): Lexer.Token;
export declare function sridLiteral(value: number[], index: number): Lexer.Token;
export declare function pointLiteral(value: number[], index: number): Lexer.Token;
export declare function polygonLiteral(value: number[], index: number): Lexer.Token;
export declare function collectionLiteral(value: number[], index: number): Lexer.Token;
export declare function lineStringLiteral(value: number[], index: number): Lexer.Token;
export declare function multiLineStringLiteral(value: number[], index: number): Lexer.Token;
export declare function multiPointLiteral(value: number[], index: number): Lexer.Token;
export declare function multiPolygonLiteral(value: number[], index: number): Lexer.Token;
export declare function multiGeoLiteralFactory(value: number[], index: number, prefix: string, itemLiteral: Function): Lexer.Token;
export declare function multiGeoLiteralOptionalFactory(value: number[], index: number, prefix: string, itemLiteral: Function): Lexer.Token;
export declare function geoLiteral(value: number[], index: number): Lexer.Token;
export declare function fullPointLiteral(value: number[], index: number): Lexer.Token;
export declare function fullCollectionLiteral(value: number[], index: number): Lexer.Token;
export declare function fullLineStringLiteral(value: number[], index: number): Lexer.Token;
export declare function fullMultiLineStringLiteral(value: number[], index: number): Lexer.Token;
export declare function fullMultiPointLiteral(value: number[], index: number): Lexer.Token;
export declare function fullMultiPolygonLiteral(value: number[], index: number): Lexer.Token;
export declare function fullPolygonLiteral(value: number[], index: number): Lexer.Token;
export declare function fullGeoLiteralFactory(value: number[], index: number, literal: Function): Lexer.Token;
export declare function geographyCollection(value: number[], index: number): Lexer.Token;
export declare function geographyLineString(value: number[], index: number): Lexer.Token;
export declare function geographyMultiLineString(value: number[], index: number): Lexer.Token;
export declare function geographyMultiPoint(value: number[], index: number): Lexer.Token;
export declare function geographyMultiPolygon(value: number[], index: number): Lexer.Token;
export declare function geographyPoint(value: number[], index: number): Lexer.Token;
export declare function geographyPolygon(value: number[], index: number): Lexer.Token;
export declare function geometryCollection(value: number[], index: number): Lexer.Token;
export declare function geometryLineString(value: number[], index: number): Lexer.Token;
export declare function geometryMultiLineString(value: number[], index: number): Lexer.Token;
export declare function geometryMultiPoint(value: number[], index: number): Lexer.Token;
export declare function geometryMultiPolygon(value: number[], index: number): Lexer.Token;
export declare function geometryPoint(value: number[], index: number): Lexer.Token;
export declare function geometryPolygon(value: number[], index: number): Lexer.Token;
export declare function geoLiteralFactory(value: number[], index: number, type: string, prefix: Function, literal: Function): Lexer.Token;
export declare function primitiveLiteral(value: number[], index: number): Lexer.Token;
